# Generated by Django 6.0.1 on 2026-01-13 15:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('speed', models.FloatField(default=0.0)),
                ('is_moving', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('destination_latitude', models.FloatField(blank=True, null=True)),
                ('destination_longitude', models.FloatField(blank=True, null=True)),
                ('payment_method', models.CharField(choices=[('ecocash', 'Ecocash'), ('debit_card', 'Debit Card')], max_length=20)),
                ('fare_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('onboard', 'Onboard'), ('outside', 'Outside (Restroom)'), ('alighted', 'Alighted')], default='onboard', max_length=20)),
                ('boarded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('alighted_at', models.DateTimeField(blank=True, null=True)),
                ('went_outside_at', models.DateTimeField(blank=True, null=True)),
                ('returned_inside_at', models.DateTimeField(blank=True, null=True)),
                ('is_overdue', models.BooleanField(default=False)),
                ('last_notified_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_popular', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('payment_confirmed', 'Payment Confirmed'), ('restroom_left_behind', 'Passenger Left Behind'), ('approaching_destination', 'Approaching Destination'), ('overdue_passenger', 'Overdue Passenger'), ('thank_you', 'Thank You')], max_length=30)),
                ('message', models.TextField()),
                ('is_played', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('played_at', models.DateTimeField(blank=True, null=True)),
                ('passenger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='passengers.passenger')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=20)),
                ('transaction_id', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('status', models.CharField(default='completed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='passengers.passenger')),
            ],
        ),
        migrations.AddField(
            model_name='passenger',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='passengers.stop'),
        ),
    ]
